### ISSUE TITLE
OLAP support in Doradus

### ISSUE THREAD

**Issue by agonen** [dell-oss/Doradus#11]
hi all, I see OLAP mention a lot in the documentation , but most of the document talk and example  about columnar db .
I wander (maybe I missed it ) if you've support  for [OLAP Cube!](https://en.wikipedia.org/wiki/OLAP_cube).  I'm especially interested in the "roll-up" capabilities.

I would also like also to discuss  on offline (my mail is agonenil at gmail...)  threat  a use case that we are considering to use doradus.

**Comment by RandyGuck** [comment]
OK, I'll email with you offline.
