### ISSUE TITLE
error using the example

### ISSUE THREAD

**Issue by agonen** [dell-oss/Doradus#5]
Hi I've installed Doradus using docker and using the example : 

curl -H "content-type: application/json" -d '{"Stuff": {}}' http://172.17.0.1:1123/_applications

i'm getting the following error:
application definition missing 'key' definition

**Comment by RandyGuck** [comment]
Hi,

It looks like the Docker module is using an older version of Doradus that used to require an application “key”. Until Tra updates it to a newer release, you can use this command instead:

curl -H "content-type: application/json" -d '{"Stuff": {"key": "xyz"}}' http://172.17.0.1:1123/_applications

This sets the application’s key to “xyz”. Later, if you want to delete the application, use the command:

curl -X delete http://172.17.0.1:1123/_applications/Stuff/xyz

Thanks,

Randy Guck
Principal Engineer
Dell Software Group
office +1 949 754 8237
fax +1 949 754 8999

**Comment by TraDuong1** [comment]
I am not sure which dockerized Doradus you use, but the latest one we recommend to use is

https://github.com/dell-oss/Doradus/tree/master/doradus-docker

This will use the latest check out and build of Doradus .

For ex: this doesn’t use the application “key” at all

curl -H "content-type: application/json" -d '{"Stuff": {}}' http://ec2-52-3-219-151.compute-1.amazonaws.com:8080/_applications

**Comment by agonen** [comment]
thanks for the quick feed back.

I'm try to pull the docker and get

root@vagrant-ubuntu-trusty-64:~# docker run -p 1123:1123 -d --name doradus
-v /srv/cassandra:/var/lib/cassandra traduong1/docker-doradus
Unable to find image 'traduong1/docker-doradus:latest' locally
Pulling repository traduong1/docker-doradus
Error: image traduong1/docker-doradus:latest not found

**Comment by TraDuong1** [comment]
We only have 1 project doradus-docker under dell-oss now. The docker project that uses Cassandra DB is obsolete, so we remove it from docker hub. Please check the instructions of how to use the latest project at
https://github.com/dell-oss/Doradus/tree/master/doradus-docker

Thanks.

**Comment by agonen** [comment]
thanks.
Just to understand , is cassandara is not supported with Doradus ? or only
the docker project ?

do I need to deploy it on AWS or can I install it on vagrant (virtualbox
machine )?

**Comment by TraDuong1** [comment]
Cassandra is still being the main noSQL DB supported by Doradus server outside of Docker env.
Having 2 docker projects are confusing and so the latest one mainly focuses on DynamoDB noSQL DB.

You can deploy on any Docker-base env (Linux, Mac, etc), doesn’t have to be AIM.

**Comment by agonen** [comment]
ok . thanks
