### ISSUE TITLE
unable to merge shards

### ISSUE THREAD

**Issue by sivankar** [dell-oss/Doradus#9]
Hi. im working on OLAP. im not able to merge the shards. im using the Doradus-jetty REST api's.
when i run the merge REST api it say.Application does not exist or does not have merges yet.

and when i run the api for application listing. its shows my application. can you please help me with shard merging.

**Comment by RandyGuck** [comment]
It sounds like the shard you're trying to merge doesn't have any data yet. Be sure batches are loaded with POST /{application}/{shard} where {shard} is the target shard name. After at least one batch is loaded, use POST /{application}/_shards/{shard} using the same shard name. If the application or shard name have any non-alphanumeric characters, there may be some URI encoding issues. I'd be happy to look at your example.

**Comment by sivankar** [comment]
well i tried to load a batch with post command curl -h "content-type : application/json" -d @test.json http:localhost:1123/{application}/{shard}
... the shard it created and it says the batch result ok and returns me a GUID. and im not able to see any data in cassandra even in "Doradus"."OLAP".
if u can help me loading a batch data properly may be that would resolve the issue

**Comment by RandyGuck** [comment]
Hi Sivankar,

I just tried a test and everything seems to be working. Here are some things to watch for:

1) In curl, use -H (not -h) to add a header.
2) Be sure the "doc" elements in your input batch include a "_table" field to indicate which table each object should be added to.
3) If the curl command completes successfully, you should see a result such as:
{"batch-result":{"status":"OK","comment":"GUID=19tgiiq4q-bfbf9ba6-7e9d-4d07-b8b7-9ff64abe6e70"}}
4) Even before merging the shard, you can perform a query and include un-merged data to verify that it is there. Here's an example URL with my test DB:

http://localhost:1123/Test/T1/_query?q=*&shards=S1&uncommitted=true

Note that Test is the app name, T1 is the table, and S1 is the shard name. "uncommitted=true" includes un-merged batches (new feature we just recently added!)

Let me know if you need further help.

**Comment by sivankar** [comment]
so you mean once i load a bacth the data will be loaded. then why im not able to merge it?
and until i merge it im not able to see shards statistics and query... n how will i fire aggregate query with out merging?

**Comment by RandyGuck** [comment]
Normally you *should* merge all loaded batches into the "live" shard with the command: POST /Test/_shards/S1. You should see a 200 OK response with no output body for this command. Then, when you query the shard with `GET /Test/T1/_query?q=*&shards=S1` or `GET /Test/T1/_aggregate?q=*&shards=S1&m=COUNT(*)` you'll only query "live" objects. However, we recently added the option `&uncommitted=true` so you can include un-merged objects in the query in addition to the "live" objects. However, this option has some caveats, which I'm in the process of documenting. (New docs coming soon.) Just ignore this option if you like. If you're still having trouble merging, let me know the full REST command you're using and the response returned by curl.

**Comment by sivankar** [comment]
but today i was trying to build recent code with maven it was not able to download all the jar files and i could not use the recent deployment

**Comment by sivankar** [comment]
This is the Example i tried.

1) application structure.
curl -H "content-type: text/xml" -d '<application name="EmployeeDB"><key>EmployeeKey</key><options><option name="StorageService">OLAPService</option></options><tables><table name="EmployeeData"><fields><field name="E_Name" type="Text"/><field name="Age" type="integer" /></fields></table></tables></application>' http://localhost:1123/_applications

2) batch : 

 curl -H "content-type: application/json" -d '{"batch": {"docs": [{"doc": {"_table":"EmployeeData","E_Name": "Shreyas","Age": 22}},{"doc": {"_table":"EmployeeData","E_Name": "raji","Age": 56}}]}}' http://localhost:1123/EmployeeDB/Dataset1

Response: 
{"batch-result":{"status":"OK","comment":"GUID=19thke239-52852839-475c-4fce-8e4d-e7e8bc1b4bc9"}}

3) query:

 curl -H "content-type: application/json" http://localhost:1123/EmployeeDB/EmployeeData/_query?shards=Dataset1&q=*

response {"results":{"totalobjects":"0","docs":[]}}

4) shard merging 

 curl -H "content-type: application/json" http://localhost:1123/EmployeeDB/_shards/Dataset1

response : Application does not exist or does not have merges yet


can you please look into it and guid me where im going wrong.

**Comment by RandyGuck** [comment]
Hi Sivankar: I believe the problem you're having in step 4) is that the command needs to be a POST. Add "-X POST" to your curl command and it should work. Without the -X parameter, curl defaults to GET, so the command becomes GET /{application}/_shards/{shard}, which is a "get shard statistics" command. It returns an error because there is no merged data in that shard yet. BTW in step 1), I presume you used had an @ symbol before 'EmployeeKeyOLAPService', which is a file name containing the schema?

**Comment by sivankar** [comment]
application name="EmployeeDB">key>EmployeeKey</key>options>option name="StorageService">OLAPService</option></options>tables>table name="EmployeeData">fields>field name="E_Name" type="Text"/>field name="Age" type="integer" /></fields></table></tables></application>


i have remover the '<' it was xml so it was not visible before. 
and even if i use -POST in step 4 it gives me the same response.

**Comment by sivankar** [comment]
hey, Thanks its working with the "-X POST"

**Comment by RandyGuck** [comment]
No problem. Let me know if you have any other questions or issues.

**Comment by sivankar** [comment]
hi, im facing issue while querying.

Query : 
1) curl -H "content-type: text/xml" http://localhost:1123/EmployeeDB/_statistics/Dataset1

   response : {"statistics":{"files":[{"file":{"name":"EmployeeData.Age.dat","cmp":"4","unc":"4"}},{"file":{"name":"EmployeeData.E_Name.doc","cmp":"3","unc":"3"}},{"file":{"name":"EmployeeData.E_Name.orig","cmp":"15","unc":"15"}},{"file":{"name":"EmployeeData.E_Name.orig.idx","cmp":"6","unc":"6"}},{"file":{"name":"EmployeeData.E_Name.term","cmp":"15","unc":"15"}},{"file":{"name":"EmployeeData.E_Name.term.idx","cmp":"6","unc":"6"}},{"file":{"name":"EmployeeData._id","cmp":"36","unc":"36"}},{"file":{"name":"EmployeeData.idx","cmp":"22","unc":"22"}},{"files":"8"},{"cmp":"107"},{"unc":"107"}],"tables":[{"table":{"name":"EmployeeData","docs":"2","id-field":{"ids_mem":"1,072"},"num-fields":[{"num":{"name":"Age","mem":"30"}},{"flds":"1"},{"num_mem":"30"}],"txt-fields":[{"fld":{"name":"E_Name","mem":"24"}},{"cnt":"1"},{"fld_mem":"24"}],"val-fields":[{"val":{"name":"E_Name","mem":"1,048"}},{"flds":"1"},{"val_mem":"1,048"}],"lnk-fields":[{"flds":"0"},{"lnk_mem":"0"}],"flds":"2","mem":"2,174"}},{"docs":"2"},{"memory":"2,174"},{"fields":"2"}]}}


now when i try to query

2)  curl -H "content-type: text/xml" http://localhost:1123/EmployeeDB/EmployeeData/_query?q=*&shards=Dataset1

  response:-  shards or range parameter is not set

3) but, curl -H "content-type: application/json" http://localhost:1123/EmployeeDB/EmployeeData/_query?shards=Dataset1&q=*

response: return all the rows in the table,

the query on the serve side curl -H "content-type: application/json" http://localhost:1123/EmployeeDB/EmployeeData/_query?shards=Dataset1
is executed and i.e all the rows are return.

but im not able to figure out why is step 2 not working when _query/q=*&shards=Dataset1

**Comment by RandyGuck** [comment]
The issue when using curl in shell commands is that '&' is picked-up by the shell. So in your example in 2), quote the entire URL. Example:

curl -H "content-type: text/xml" 'http://localhost:1123/EmployeeDB/EmployeeData/_query?q=*&shards=Dataset1'

If entered from the command line, 3) should fail with the same problem as 2) unless you quote the URL. Maybe you entered that command from a browser? (All GET commands can be entered via a browser.)

**Comment by sivankar** [comment]
hey,
thanks its working fine now. :)
